name: "Lint"
description: "Lint TypeScript and Python code"

inputs:
    node_version:
        description: "Version of Node to install"
        required: true

runs:
    using: "composite"
    steps:
        - name: Install Node
          uses: actions/setup-node@v2
          with:
              node-version: ${{ inputs.node_version }}
              cache: "npm"

        - name: Install Node dependencies
          run: npm ci --prefer-offline
          shell: bash

        - name: Run `gulp prePublishNonBundle`
          run: npx gulp prePublishNonBundle
          shell: bash

        - name: Check Typescript Formatting
          run: |
              npm install -g prettier
              prettier --check "src/**/*.ts"
          working-directory: pythonFiles
          shell: bash
